<script setup lang="ts">
import { computed, nextTick, ref, watch } from 'vue'
import type { MediaAssetCollectionResponse, MediaAssetResponse } from '@/types/admin-api'
import { fetchJson } from '@/utils/request-helpers'

const props = defineProps<{ modelValue: string; readonly?: boolean }>()
const emit = defineEmits<{ 'update:modelValue': [value: string] }>()
const open = ref(false); const loading = ref(false); const error = ref<string | null>(null); const assets = ref<MediaAssetResponse[]>([]); const search = ref(''); const highlighted = ref<string | null>(props.modelValue || null); const searchRef = ref<HTMLInputElement | null>(null)
const visible = computed(() => assets.value.filter(asset => `${asset.fileName} ${asset.title ?? ''} ${asset.altText ?? ''}`.toLowerCase().includes(search.value.toLowerCase())))
const selected = computed(() => assets.value.find(asset => asset.id === props.modelValue) ?? null)
watch(open, value => { if (value) nextTick(() => searchRef.value?.focus()) })
async function showPicker() { open.value = true; loading.value = true; error.value = null; try { assets.value = (await fetchJson<MediaAssetCollectionResponse>('/api/v1/media/assets')).assets; highlighted.value = props.modelValue || null } catch (caught) { error.value = caught instanceof Error ? caught.message : 'Media could not be loaded.' } finally { loading.value = false } }
function confirm() { if (highlighted.value) emit('update:modelValue', highlighted.value); open.value = false }
</script>
<template>
  <div class="image-picker">
    <div v-if="selected" class="image-picker__selected"><img :src="selected.contentUrl" :alt="selected.altText ?? ''" /><div><strong>{{ selected.title || selected.fileName }}</strong><small>{{ selected.altText || 'No alt text set' }}</small></div><button v-if="!readonly" type="button" @click="showPicker">Browse</button><button v-if="!readonly" type="button" @click="emit('update:modelValue', '')">Clear</button></div>
    <button v-else-if="!readonly" class="image-picker__empty" type="button" @click="showPicker">Choose image from media library...</button><p v-else class="image-picker__muted">No image selected.</p>
    <Teleport to="body"><div v-if="open" class="image-picker__backdrop" role="dialog" aria-modal="true" aria-label="Media library" @click.self="open = false" @keydown.escape="open = false"><div class="image-picker__modal"><header><strong>Media Library</strong><input ref="searchRef" v-model="search" type="search" placeholder="Search media" /><button type="button" aria-label="Close" @click="open = false">x</button></header><main role="listbox" @keydown.enter.prevent="confirm"><p v-if="loading">Loading media...</p><p v-else-if="error">{{ error }}</p><p v-else-if="visible.length === 0">{{ search ? 'No search results.' : 'This folder is empty.' }}</p><button v-for="asset in visible" v-else :key="asset.id" role="option" :aria-selected="highlighted === asset.id" :tabindex="highlighted === asset.id ? 0 : -1" :class="{ selected: highlighted === asset.id }" @click="highlighted = asset.id" @dblclick="highlighted = asset.id; confirm()"><img :src="asset.contentUrl" :alt="asset.altText ?? ''" /><span>{{ asset.title || asset.fileName }}</span></button></main><footer><span>{{ highlighted ? 'Enter or double-click to confirm.' : 'Choose an image.' }}</span><button type="button" @click="open = false">Cancel</button><button type="button" :disabled="!highlighted" @click="confirm">Select</button></footer></div></div></Teleport>
  </div>
</template>
<style scoped>
.image-picker__empty,.image-picker__selected{width:100%;border:1px dashed #d6d3d1;border-radius:.75rem;padding:.75rem;background:#fff;text-align:left}.image-picker__selected{display:flex;gap:.75rem;align-items:center;border-style:solid}.image-picker__selected img{width:5rem;height:3.5rem;object-fit:cover;border-radius:.35rem}.image-picker__selected small{display:block;color:#78716c}.image-picker__selected button{margin-left:auto}.image-picker__backdrop{position:fixed;inset:0;z-index:50;display:grid;place-items:center;background:#0008;padding:1.5rem}.image-picker__modal{width:min(48rem,100%);height:min(32rem,100%);display:flex;flex-direction:column;background:#fff;border-radius:1rem;overflow:hidden}.image-picker__modal header,.image-picker__modal footer{display:flex;gap:.75rem;align-items:center;padding:1rem;border-bottom:1px solid #e7e5e4}.image-picker__modal header input{margin-left:auto}.image-picker__modal main{flex:1;overflow:auto;padding:1rem;display:grid;grid-template-columns:repeat(auto-fill,minmax(8rem,1fr));gap:.75rem}.image-picker__modal main button{border:1px solid #e7e5e4;border-radius:.5rem;text-align:left;overflow:hidden}.image-picker__modal main button.selected{outline:2px solid #5970e3}.image-picker__modal main img{width:100%;height:5.5rem;object-fit:cover}.image-picker__modal main span{display:block;padding:.4rem;font-size:.75rem}.image-picker__modal footer{border-top:1px solid #e7e5e4;border-bottom:0}.image-picker__modal footer span{margin-right:auto}.image-picker__muted{color:#a8a29e;font-style:italic}
</style>
